#ifndef COMMON_HXX_
#define COMMON_HXX_

//Exit codes (other than EXIT_SUCCESS)
#define EXIT_PARSE_ERROR_IN_USER_LIBRARY 1
#define EXIT_PARSE_ERROR_IN_INPUT 2
#define EXIT_EXEC_ERROR_IN_USER_LIBRARY 3
#define EXIT_EXEC_ERROR_IN_INPUT 4
#define EXIT_PLATFORM_ERROR 5
#define EXIT_INCORRECT_USAGE 254
#define EXIT_THE_SKY_IS_FALLING 255

#endif /* COMMON_HXX_ */
